import 'package:flutter/cupertino.dart';
import 'package:pdf_creator/pdf_templates/pdf_template_16_1_29/pdf_template_16_1_29.dart';
import 'package:printing/printing.dart';

import 'pdf_viewer_screen.props.dart';

class PdfViewerScreen extends StatelessWidget {
  const PdfViewerScreen({Key? key, required this.props}) : super(key: key);

  final PdfViewerScreenProps props;

  @override
  Widget build(BuildContext context) {
    return PdfPreview(
        build: (format) =>
            props.pdf ??
            PdfTemplate16129([
              [
                '1999/01/22',
                '1999/01/22',
                '1999/01/22',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1', // 10
                '1',
                '1',
                '1',
                'q',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1', // 20
                '2022/12/22',
                '2022/12/22',
                '1',
                '1',
                '1',
                '1',
                '1',
                '2022/12/22',
                '1',
                '2022/12/22', // 30
                '2022/12/22',
                '2022/12/22',
                '1',
                '1',
                '1',
                '2022/12/22',
                '1',
                '1',
                '2022/12/22',
                '1', // 40
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1', // 50
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
              ],
              [
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1'
              ],
            ]).build());
  }
}
